[package]
name = "sufaceflinger_hook"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
android_logger = "0.13.3"
dobby-sys = { git = "https://github.com/lanylow/dobby-sys.git" }
libc = "0.2.147"
log = "0.4.19"
